name: Update Download Badge

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  push:
    branches:
      - main

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch download counts and update badge
        run: |
          TOTAL_DOWNLOADS=$(curl -s https://api.github.com/repos/mcpebd/mcpebd/releases | jq '[.[] | .assets[] | select(.browser_download_url == "https://github.com/mcpebd/mcpebd/releases/download/MCPE/Minecraft_1.21.1.03_arm-v7a_952100103.apk" or .browser_download_url == "https://github.com/mcpebd/mcpebd/releases/download/MCPE/Minecraft_1.21.1.03_arm-v8a_972100103.apk" or .browser_download_url == "https://github.com/mcpebd/mcpebd/releases/download/MCPE/Minecraft_1.21.1.03_chromeOS_1982100103.apk" or .browser_download_url == "https://github.com/mcpebd/mcpebd/releases/download/MCPE/Minecraft_1.21.1.03_noMusic_arm-v7a_952100103.apk" or .browser_download_url == "https://github.com/mcpebd/mcpebd/releases/download/MCPE/Minecraft_1.21.1.03_noMusic_arm-v8a_972100103.apk") | .download_count] | add')
          BADGE_URL="https://img.shields.io/badge/downloads-${TOTAL_DOWNLOADS}-blue"
          echo "${BADGE_URL}"

          # Update README.md with the new badge URL
          sed -i 's|!\[Downloads\](https://img.shields.io/badge/downloads-[0-9]\+-blue)|![Downloads](${BADGE_URL})|' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update download badge'
          git push
